clf, clear
h6=figure(1);
R=0;G=0.4;B=0;
set(h6,'Position',[60, 300,580,380],...
       'Color',[ 0.7,0.7,0.7],...
       'NumberTitle','off',...
       'Name','单缝衍射实验的计算机模拟')
axes( 'Position', [0.43 0.2, 0.55 0.55],...
      'Box', 'on', 'Color','k')
Lambda=0.0006328;f=64;a=0.02;
Dfys_m(Lambda,f,a)
%======= 'Fontname','Times NewRoman'系统需要支持文本框所设置的字体属性
t1 = uicontrol(gcf,'Style','text', ...
   'String','    单缝衍射的光强分布为： I = I(0) ( sin α ) ^ 2 / α ^ 2',...
   'HorizontalAlignment','Left',...
   'Position',[150,363,280,15],...
   'BackgroundColor',[1,0.8,0.8]);
t1B= uicontrol(gcf,'Style','text', ...
   'String',...
      ['光波波长 λ (mm) = ',num2str(Lambda)],...
   'HorizontalAlignment','Left',...
   'Position',[30,315,180,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t2 = uicontrol(gcf,'Style','text', ...
   'String',...
      ['屏幕前透镜的焦距 f (mm) = ',num2str(f)],...  
   'HorizontalAlignment','Left',...
   'Position',[210,315,180,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t2B = uicontrol(gcf,'Style','text', ...
   'String',...
      ['缝的光度 a (mm) = ',num2str(a)],...
   'HorizontalAlignment','Left',...
   'Position',[400,315,180,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
%=============================Edit for Lambda 
b1 = uicontrol(gcf,'Style','text', ...
   'String','光波波长 λ (mm) : ',...
   'Position',[30,245,90,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
b2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[120,248,80,20], ...
   'String',...
   [num2str(Lambda)],...
   'CallBack',...
   ['cla;Lambda=str2num(get(b2,''String''));',...
    'set(t1B,''String'',[''光波波长 λ (mm) =  '',num2str(Lambda)]);',...
]);
 %=============================Edit for f 
m1 = uicontrol(gcf,'Style','text', ...
   'String','透镜焦距 f (mm) : ',...
   'Position',[30,185,90,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
m2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[120,188,80,20], ...
   'String', ...
   [num2str(f)],...
   'CallBack',...
  ['cla;f=str2num(get(m2,''String''));',...
   'set(t2,''String'',[''屏幕前透镜的焦距 f (mm) = '',num2str(f)]);',...
]);
 %=============================Edit for a
n1 = uicontrol(gcf,'Style','text', ...
   'String','缝的光度 a (mm) :',...
   'Position',[30,125,90,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
n2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[120,128,80,20], ...
   'String', ...
   [num2str(a)],...
   'CallBack', ...
   ['cla;a=str2num(get(n2,''String''));',...
    'set(t2B,''String'',[''缝的光度 a (mm) = '',num2str(a)]);',...
]);
%================================ Push button
x1 = uicontrol(gcf,'Style','push',...
   'String','退出',...
   'Position',[370,15,80,30],...
   'Callback','close');
x2 = uicontrol(gcf,'Style','push',...
   'String','单缝衍射  ',...
   'Position',[15,55,80,30],...
   'Callback','Dfys_m1(Lambda,f,a)');
x3= uicontrol(gcf,'Style','push',...
   'String','光强分布  ',...
   'Position',[140,55,80,30],...
   'Callback','Dfys_m(Lambda,f,a)');