h_line=line('XData',[0 82],'YData',[-2.4 -2.4],'LineStyle','-','LineWidth',3);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[0.2 0.2],'YData',[-2.4 10],'LineStyle','-','LineWidth',3);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[0.3 82],'YData',[-1.2 -1.2],'LineStyle','--');
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[0.3 82],'YData',[0.0 0.0],'LineStyle','--');
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[0.3 82],'YData',[1.2 1.2],'LineStyle','--');
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[0.3 82],'YData',[2.4 2.4],'LineStyle','--');
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[0.3 82],'YData',[3.6 3.6],'LineStyle','--');
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[0.3 82],'YData',[4.8 4.8],'LineStyle','--');
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[40 40],'YData',[-1.5 10],'LineStyle','--');
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[80 77],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[78 75],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[76 73],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[74 71],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[72 69],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[70 67],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[68 65],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[66 63],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[64 61],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[62 59],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[60 57],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[58 55],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[56 53],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[54 51],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[52 49],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[50 47],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[48 45],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[46 43],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[44 41],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[42 39],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[40 37],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[38 35],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[36 33],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[34 31],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[32 29],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[30 27],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[28 25],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[26 23],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[24 21],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[22 19],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[20 17],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[18 15],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[16 13],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[14 11],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[12 9],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[10 7],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[8 5],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[6 3],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');
h_line=line('XData',[4 1],'YData',[-2.4 -3.2],'LineStyle','-','LineWidth',2);
set(h_line,'HandleVisibility','callback');

