clf reset
% 界面设计与程序调用
H=axes('unit','normalized','position',[0.02,0,1,1],'visible','off');
set(gcf,'currentaxes',H);
str='单自由度振子运动演示';
text(0.24,0.93,str,'fontsize',13);
h_fig=get(H,'parent');
set(h_fig,'unit','normalized','position',[0.01 0.49 0.98 0.45],...
       'NumberTitle','off',...
       'Name','振动试验数值仿真软件');
h_axes=axes('parent',h_fig,...
    'unit','normalized','position',[0.03 0.54 0.64 0.35],...
    'xlim',[0 80],'ylim',[-2 2],'fontsize',8,'visible','off');
hf1=figure(1);
FrmBKcolor=[0.2 0.5 0.5];
frm1left=0.68;frm1btm=0.35;frm1wid=0.32;frm1het=0.73;
frm1Pos=[frm1left frm1btm frm1wid frm1het];
h=uicontrol(hf1,'Style','frame','unit','normalized',...
    'Position',frm1Pos,'BackgroundColor',FrmBKcolor);
hf1=figure(1);
FrmBKcolor=[0.2 0.5 0.5];
frm1left=0.03;frm1btm=0.15;frm1wid=0.64;frm1het=0.25;
frm1Pos=[frm1left frm1btm frm1wid frm1het];
h=uicontrol(hf1,'Style','frame','unit','normalized',...
    'Position',frm1Pos,'BackgroundColor',FrmBKcolor);
Initial
%============================
e1=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.39,0.29,0.26,0.05],...
    'horizontal','left','string',{'                              位移 x(cm) =  '});
e1B=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.39,0.24,0.26,0.05],...
    'horizontal','left','string',{'                              速度v(m/s) =  '});
e2=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.39,0.19,0.26,0.05],...
    'horizontal','left','string',{'                       加速度a(m/s^2)=  '});
e2B=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.22,0.29,0.149,0.05],...
    'horizontal','left','string',{' 按下求解按钮求解运动状态'});
%============================Edit for L0 
L1=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.69,0.92,0.08,0.05],...
    'horizontal','left','string',{' 弹簧原长 L0 ='});
L2=uicontrol(gcf,'style','edit',...
    'unit','normalized','backgroundColor','w','position',[0.77,0.92,0.05,0.05],...
    'horizontal','left',...
    'callback',['LO=str2num(get(L2,''string''));',...
        'hold off,']);
%============================Edit for w0 
w3=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.86,0.92,0.08,0.05],...
    'horizontal','left','string',{' 固有频率   = '});
w4=uicontrol(gcf,'style','edit',...
    'unit','normalized','backgroundColor','w','position',[0.94,0.92,0.05,0.05],...
    'horizontal','left',...
    'callback',['w0=str2num(get(w4,''string''));',...
        'hold off,']);
%============================Edit for x0
x1=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.69,0.83,0.08,0.05],...
    'horizontal','left','string',{' 初位移 x0(cm)= '});
x2=uicontrol(gcf,'style','edit',...
    'unit','normalized','backgroundColor','w','position',[0.77,0.83,0.05,0.05],...
    'horizontal','left',...
    'callback','x0=str2num(get(x2,''string''));');
%============================Edit for v0 
v1=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.86,0.83,0.08,0.05],...
    'horizontal','left','string',{' 初速度v0(m/s)= '});
v2=uicontrol(gcf,'style','edit',...
    'unit','normalized','backgroundColor','w','position',[0.94,0.83,0.05,0.05],...
    'horizontal','left',...
    'callback','v0=str2num(get(v2,''string''));');
%============================Edit for m 
m1=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.69,0.73,0.08,0.05],...
    'horizontal','left','string',{' 质量  m ( kg ) =  '});
m2=uicontrol(gcf,'style','edit',...
    'unit','normalized','backgroundColor','w','position',[0.77,0.73,0.05,0.05],...
    'horizontal','left',...
    'callback',[...
        'm=str2num(get(m2,''string''));',...
        'hold off,']);
%============================Edit for k 
k1=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.86,0.73,0.08,0.05],...
    'horizontal','left','string',{' 刚度   k(N/m) =  '});
k2=uicontrol(gcf,'style','edit',...
    'unit','normalized','backgroundColor','w','position',[0.94,0.73,0.05,0.05],...
    'horizontal','left',...
    'callback',[...
        'k=str2num(get(k2,''string''));',...
        'hold off,']);
%============================Edit for c 
c1=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.69,0.61,0.08,0.07],...
    'horizontal','left','string',{'     阻尼系数  ','    c ( N/m ) = '});
c2=uicontrol(gcf,'style','edit',...
    'unit','normalized','backgroundColor','w','position',[0.77,0.61,0.05,0.07],...
    'horizontal','left',...
    'callback',[...
        'c=str2num(get(c2,''string''));',...
        'hold off,']);
%============================Edit for beta 
beta1=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.86,0.61,0.08,0.07],...
    'horizontal','left','string',{'   非线性系数  ','         beta  = '});
beta2=uicontrol(gcf,'style','edit',...
    'unit','normalized','backgroundColor','w','position',[0.94,0.61,0.05,0.07],...
    'horizontal','left',...
    'callback',[...
        'beta=str2num(get(beta2,''string''));',...
        'hold off,']);
%============================Edit for F0 
F1=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.69,0.51,0.08,0.05],...
    'horizontal','left','string',{' 激励力 F0(N) = '});
F2=uicontrol(gcf,'style','edit',...
    'unit','normalized','backgroundColor','w','position',[0.77,0.51,0.05,0.05],...
    'horizontal','left',...
    'callback',[...
    'F0=str2num(get(F2,''string''));',...
    'hold off,']);
%============================Edit for w 
w1=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.86,0.51,0.08,0.05],...
    'horizontal','left','string',{' 激励频率  w = '});
w2=uicontrol(gcf,'style','edit',...
    'unit','normalized','backgroundColor','w','position',[0.94,0.51,0.05,0.05],...
    'horizontal','left',...
    'callback',[...
    'w=str2num(get(w2,''string''));',...
    'hold off,']);
%============================Edit for t11 
t5=uicontrol(gcf,'style','text',...
    'unit','normalized','position',[0.05,0.29,0.15,0.05],...
    'horizontal','left','string',{'请在下框中输入某一时刻值'});
t6=uicontrol(gcf,'style','edit',...
    'unit','normalized','backgroundColor','w','position',[0.05,0.21,0.15,0.08],...
    'horizontal','left',...
    'Callback',[...
    'cla;',...
    't11=str2num(get(t6,''string''));',... 
    '[a,a1,a2]=accel(x0,v0,t,m,k,c,F0,w,w0,beta,t11);',...
    'set(e2,''String'',[''                        加速度a(m/s^2)=   '',num2str(a)]);',...
    'set(e1,''String'',[''                                位移 x(cm) =  '',num2str(a2)]);',...
    'set(e1B,''String'',[''                               速度v(m/s) =  '',num2str(a1)]);']);
%============================Slider for t 
t3B= uicontrol(gcf,'Style','text', ...
   'unit','normalized',...
   'String','拖动滑条设置演示总时间 tmax = 30 s',...
   'Position',[0.69,0.43,0.30,0.05]);
t4 = uicontrol(gcf,...
   'unit','normalized',...
   'Style','slider',...
   'Min' , 0 ,'Max', 30 , ...
   'SliderStep',[1/30 0.1], ...
   'Position',[0.69,0.38,0.30,0.05], ...
   'Value', 0,...
   'CallBack', ...
     [ 'cla;t=get(t4,''Value'');','hold off,']);
%================================ Push button
b1 = uicontrol(gcf,'Style','Push', ...
   'String','绘图',...
   'unit','normalized',...
   'Position',[0.69,0.23,0.08,0.08],...
   'CallBack','startdown');
b2 = uicontrol(gcf,'Style','Push', ...
   'String','运动演示',...
   'unit','normalized',...
   'Position',[0.795,0.23,0.08,0.08],...
   'CallBack','draw');
b3 = uicontrol(gcf,'Style','Push', ...
   'String','恢复原态',...
   'unit','normalized',...
   'Position',[0.795,0.08,0.08,0.08],...
   'CallBack','Initial');
b4 = uicontrol(gcf,'Style','push',...
   'unit','normalized',...
   'String','停止',...
   'Position',[0.90,0.23,0.08,0.08],...
   'Callback','pause(3);');
b5 = uicontrol(gcf,'Style','push',...
   'unit','normalized',...
   'String','清除图形',...
   'Position',[0.69,0.08,0.08,0.08],...
   'Callback','clf(figure(2))');
b6 = uicontrol(gcf,'Style','push',...
   'unit','normalized',...
   'String','关闭窗口',...
   'Position',[0.90,0.08,0.08,0.08],...
   'Callback',[...
   'close(figure(1));',...
   'close(figure(2))']);
b7 = uicontrol(gcf,'Style','push',...
   'unit','normalized',...
   'String','求解',...
   'Position',[0.22,0.21,0.15,0.08],...
   'Callback','solvedown(x0,v0,t,m,k,c,F0,w,w0,beta)');
