clf, clear
h6=figure(1);
R=0;G=0.4;B=0;
set(h6,'Position',[60, 300,680,380],...
       'Color',[ 0.7,0.7,0.7],...
       'NumberTitle','off',...
       'Name','光栅衍射实验的计算机模拟')
axes( 'Position', [0.43 0.2, 0.55 0.55],...
      'Box', 'on', 'Color','k')
Lambda=0.0006328;f=100;a=0.005;d=0.02;N=5;
Gsys_m(Lambda,f,a,d,N)
%============================= 'Fontname','Times NewRoman'系统需要支持文本框所设置的字体属性
t1 = uicontrol(gcf,'Style','text', ...
   'String','  光栅衍射的光强分布为： I = I(0) [ ( sin α ) ^ 2 / α ^ 2 ] * [ ( sin ( N u ) ) ^ 2 / ( sin u) ^ 2 ]',...
   'HorizontalAlignment','Left',...
   'Position',[70,363,450,15],...
   'BackgroundColor',[1,1,1]);
t1B= uicontrol(gcf,'Style','text', ...
   'String',...
      ['光波波长 λ (mm) = ',num2str(Lambda)],...
   'HorizontalAlignment','Left',...
   'Position',[15,325,180,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t2 = uicontrol(gcf,'Style','text', ...
   'String',...
      ['屏幕前透镜的焦距 f (mm) = ',num2str(f)],...  
   'HorizontalAlignment','Left',...
   'Position',[225,325,180,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t2B = uicontrol(gcf,'Style','text', ...
   'String',...
      ['缝的光度 a (mm) = ',num2str(a)],...
   'HorizontalAlignment','Left',...
   'Position',[435,325,180,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t3  = uicontrol(gcf,'Style','text', ...
   'String',...
      ['光栅常数 d (mm) = ',num2str(d)],...
   'HorizontalAlignment','Left',...
   'Position',[15,295,180,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t3B = uicontrol(gcf,'Style','text', ...
   'String',...
      ['缝数 N = ',num2str(N)],...
   'HorizontalAlignment','Left',...
   'Position',[225,295,180,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
%=============================Edit for Lambda 
b1 = uicontrol(gcf,'Style','text', ...
   'String','光波波长 λ (mm) : ',...
   'Position',[30,245,90,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
b2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[120,248,80,20], ...
   'String',...
   [num2str(Lambda)],...
   'CallBack',...
   ['cla;Lambda=str2num(get(b2,''String''));',...
    'set(t1B,''String'',[''光波波长 λ (mm) =  '',num2str(Lambda)]);',...
]);
 %=============================Edit for f 
m1 = uicontrol(gcf,'Style','text', ...
   'String','透镜焦距 f (mm) : ',...
   'Position',[30,195,90,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
m2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[120,198,80,20], ...
   'String', ...
   [num2str(f)],...
   'CallBack',...
  ['cla;f=str2num(get(m2,''String''));',...
   'set(t2,''String'',[''屏幕前透镜的焦距 f (mm) = '',num2str(f)]);',...
]);
 %=============================Edit for a
n1 = uicontrol(gcf,'Style','text', ...
   'String','缝的光度 a (mm) :',...
   'Position',[30,145,90,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
n2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[120,148,80,20], ...
   'String', ...
   [num2str(a)],...
   'CallBack', ...
   ['cla;a=str2num(get(n2,''String''));',...
    'set(t2B,''String'',[''缝的光度 a (mm) = '',num2str(a)]);',...
]);
%=============================Edit for d
n3 = uicontrol(gcf,'Style','text', ...
   'String','光栅常数 d (mm) :',...
   'Position',[30,95,90,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
n4 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[120,98,80,20], ...
   'String', ...
   [num2str(d)],...
   'CallBack', ...
   ['cla;d=str2num(get(n4,''String''));',...
    'set(t3,''String'',[''光栅常数 d (mm) = '',num2str(d)]);',...
]);
%=============================Edit for N
n5 = uicontrol(gcf,'Style','text', ...
   'String','缝数 N :',...
   'Position',[75,45,45,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
n6 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[120,48,80,20], ...
   'String', ...
   [num2str(N)],...
   'CallBack', ...
   ['cla;N=str2num(get(n6,''String''));',...
    'set(t3B,''String'',[''缝数 N = '',num2str(N)]);',...
]);
%=============================Popup Menu
p1 = uicontrol('Style','Popup', ...
   'String',...
      ' N = 1| N = 5 | N = 10 | N =15 | N = 20 ',...
   'Position',[595,360,80,20],...
   'Value',2,...
   'CallBack',...
   [...
    ' cla;cv=get(p1,''Value'');'...
    ' if cv==1, N=1; end;'...
    ' if cv==2, N=5; end;'...
    ' if cv==3, N=10; end;'...
    ' if cv==4, N=15; end;'...
    ' if cv==5, N=20; end;'...
    ' set(n6, ''String'',[num2str(N)]);',...
    ' set(t3B,''String'',[''缝数 N = '',num2str(N)]);',...
   ]);
%================================ Push button
x1 = uicontrol(gcf,'Style','push',...
   'String','退出',...
   'Position',[580,5,80,30],...
   'Callback','close');
x2 = uicontrol(gcf,'Style','push',...
   'String','光栅衍射  ',...
   'Position',[280,5,80,30],...
   'Callback','Gsys_m2(Lambda,f,a,d,N)');
x3= uicontrol(gcf,'Style','push',...
   'String','光强分布  ',...
   'Position',[430,5,80,30],...
   'Callback','Gsys_m(Lambda,f,a,d,N)');