% BGSA code v1.0.
% Generated by Esmat Rashedi, 2010. 
% "	E. Rashedi, H. Nezamabadi-pour and S. Saryazdi,
%“ 'BGSA: Binary Gravitational Search Algorithm', Natural Computation, vol.9, pp.727- 745, 2010."
%
%This function Evaluates the agents. 
function   fitness=evaluateF(X,F_index);

[N,dim]=size(X);
for i=1:N 
    L=X(i,:);
    %calculation of objective function
    fitness(i)=test_functions(L,F_index,dim);
end