clf, clear
h6=figure(1);
R=0;G=0.4;B=0;
set(h6,'Position',[60, 300,680,380],...
       'Color',[ 0.7,0.7,0.7],...
       'NumberTitle','off',...
       'Name','杨氏双缝干涉实验的计算机模拟')
axes( 'Position', [0.33 0.2, 0.65 0.55],...
      'Box', 'on', 'Color','k')
Lambda=0.0006328;D=1000;d1=1.0;I0=0.05;
yssfgs_m(Lambda,D,d1,I0)
%========'Fontname','Times NewRoman'系统需要支持文本框所设置的字体属性
t1 = uicontrol(gcf,'Style','text', ...
   'String','   杨氏双缝干涉的光强分布为： I(x) = 4 I(0) cos ( π d x / λ D ) ^ 2',...
   'HorizontalAlignment','Left',...
   'Position',[180,360,335,18],...
   'BackgroundColor',[1,1,1]);
t1B= uicontrol(gcf,'Style','text', ...
   'String',...
      ['光波波长 λ (mm) = ',num2str(Lambda)],...
   'HorizontalAlignment','Left',...
   'Position',[15,315,170,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t2 = uicontrol(gcf,'Style','text', ...
   'String',...
      ['光波到屏幕距离 D (mm) = ',num2str(D)],...  
   'HorizontalAlignment','Left',...
   'Position',[185,315,180,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t2B = uicontrol(gcf,'Style','text', ...
   'String',...
      ['双缝间隔 d (mm) = ',num2str(d1)],...
   'HorizontalAlignment','Left',...
   'Position',[365,315,150,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t3  = uicontrol(gcf,'Style','text', ...
   'String',...
      ['每束光波的光强 I(0) (mm) = ',num2str(I0)],...
   'HorizontalAlignment','Left',...
   'Position',[495,315,180,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
%=============================Edit for Lambda 
b1 = uicontrol(gcf,'Style','text', ...
   'String','光波波长 λ (mm) : ',...
   'Position',[15,255,90,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
b2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[105,258,80,20], ...
   'String',...
   [num2str(Lambda)],...
   'CallBack',...
   ['cla;Lambda=str2num(get(b2,''String''));',...
    'set(t1B,''String'',[''光波波长 λ (mm) =  '',num2str(Lambda)]);',...
]);
 %=============================Edit for D 
m1 = uicontrol(gcf,'Style','text', ...
   'String',{'光波到屏幕距离',' D (mm) : '},...
   'Position',[15,185,90,40],...
   'BackgroundColor',[0.7,0.7,0.7]);
m2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[105,203,80,20], ...
   'String', ...
   [num2str(D)],...
   'CallBack',...
  ['cla;D=str2num(get(m2,''String''));',...
   'set(t2,''String'',[''光波到屏幕距离 D (mm) = '',num2str(D)]);',...
]);
 %=============================Edit for d
n1 = uicontrol(gcf,'Style','text', ...
   'String','双缝间隔 d (mm) :',...
   'Position',[15,145,90,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
n2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[105,148,80,20], ...
   'String', ...
   [num2str(d1)],...
   'CallBack', ...
   ['cla;d1=str2num(get(n2,''String''));',...
    'set(t2B,''String'',[''双缝间隔 d (mm) = '',num2str(d1)]);',...
]);
%=============================Edit for I0
n3 = uicontrol(gcf,'Style','text', ...
   'String',{'每束光波的光强',' I(0) (mm) :'},...
   'Position',[15,75,90,40],...
   'BackgroundColor',[0.7,0.7,0.7]);
n4 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[105,93,80,20], ...
   'String', ...
   [num2str(I0)],...
   'CallBack', ...
   ['cla;I0=str2num(get(n4,''String''));',...
    'set(t3,''String'',[''每束光波的光强 I(0) (mm) = '',num2str(I0)]);',...
]);
%=============================Popup Menu
p1 = uicontrol('Style','Popup', ...
   'String',...
      ' d = 1.0 | d = 1.5 | d = 2.0 | d = 2.5 | d = 3.0 | d = 3.5 | d = 4.0 | d = 4.5 | d = 5.0 ',...
   'Position',[595,358,80,20],...
   'Value',1,...
   'CallBack',...
   [...
    ' cla;cv=get(p1,''Value'');'...
    ' if cv==1, d1=1.0; end;'...
    ' if cv==2, d1=1.5; end;'...
    ' if cv==3, d1=2.0; end;'...
    ' if cv==4, d1=2.5; end;'...
    ' if cv==5, d1=3.0; end;'...
    ' if cv==6, d1=3.5; end;'...
    ' if cv==7, d1=4.0; end;'...
    ' if cv==8, d1=4.5; end;'...
    ' if cv==9, d1=5.0; end;'...
    ' set(n2, ''String'',[num2str(d1)]);',...
    ' set(t2B,''String'',[''双缝间隔 d (mm) = '',num2str(d1)]);',...
   ]);
%================================ Push button
x1 = uicontrol(gcf,'Style','push',...
   'String','退出',...
   'Position',[560,5,100,30],...
   'Callback','close');
x2 = uicontrol(gcf,'Style','push',...
   'String','杨氏双缝干涉  ',...
   'Position',[220,5,100,30],...
   'Callback','yssfgs_m1(Lambda,D,d1,I0)');
x3= uicontrol(gcf,'Style','push',...
   'String','光强分布  ',...
   'Position',[390,5,100,30],...
   'Callback','yssfgs_m(Lambda,D,d1,I0)');
