clf, clear
h6=figure(1);
R=0;G=0.4;B=0;
set(h6,'Position',[60, 100,580,380],...
       'Color',[ 0.7,0.7,0.7],...
       'NumberTitle','off',...
       'Name','电磁波动态仿真')
ah=axes( 'Position', [0.50 0.3, 0.42 0.50],...
   'Box', 'on', ...
   'Color',[R,G,B],...
   'XColor',[0,0,0],'YColor',[0,0,0]);
a=1; w=1;k=1;
hb_m1(a,w,k)
%============================= 
t1 = uicontrol(gcf,'Style','text', ...
   'String',...
      ['波的振幅 a =  ',num2str(a)],...
   'HorizontalAlignment','Left',...
   'Position',[5,360,110,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t1B= uicontrol(gcf,'Style','text', ...
   'String',...
      ['波的角频率 w = ',num2str(w)],...
   'HorizontalAlignment','Left',...
   'Position',[125,360,120,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t2 = uicontrol(gcf,'Style','text', ...
   'String',...
      ['波的相位常数 k = ',num2str(k)],...                        
   'HorizontalAlignment','Left',...
   'Position',[255,360,130,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
%=============================Popup Menu
p1 = uicontrol('Style','Popup', ...
   'String',...
      'w = 1|w = 2|w = 3|w = 4|w = 5',...
   'Position',[400,360,80,20],...
   'Value',1,...
   'CallBack',...
   [...
    ' cla;cv=get(p1,''Value'');'...
    ' if cv==1, w=1; end;'...
    ' if cv==2, w=2; end;'...
    ' if cv==3, w=3; end;'...
    ' if cv==4, w=4; end;'...
    ' if cv==5, w=5; end;'...
    ' set(t1B,''String'',[''波的角频率 w =  '',num2str(w)]);',...
    ' set(m2, ''String'',[num2str(w)]);',...
   ]);
p2 = uicontrol('Style','Popup', ...
   'String',...
     'k = 1|k = 2|k = 3|k = 4|k = 5',...
   'Position',[480,360,80,20],...
   'Value',1,...
   'CallBack',...
   [...
    ' cla;cv=get(p2,''Value'');'...
    ' if cv==1, k =1; end;'...
    ' if cv==2, k =2; end;'...
    ' if cv==3, k =3; end;'...
    ' if cv==4, k =4; end;'...
    ' if cv==5, k =5; end;'...
    ' set(t2,''String'',[''波的相位常数 k =  '',num2str(k)]);',...
    ' set(n2, ''String'',[num2str(k)]);',...
   ]);
%=============================Edit for a 
b1 = uicontrol(gcf,'Style','text', ...
   'String','波的振幅 a : ',...
   'Position',[25,287,65,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
b2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[110,290,80,20], ...
   'String',...
   [num2str(a)],...
   'CallBack', ...
     [ 'cla;a=str2num(get(b2,''String''));',...
       'set(t1,''String'',[''波的振幅 t =  '',num2str(a)]);',...
     ]);
 %=============================Edit for w 
m1 = uicontrol(gcf,'Style','text', ...
   'String','波的角频率 w :',...
   'Position',[5,237,85,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
m2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[110,240,80,20], ...
   'String', ...
   [num2str(w)],...
   'CallBack', ...
     [ 'cla;w=str2num(get(m2,''String''));',...
       'set(t1B,''String'',[''波的角频率 w =  '',num2str(w)]);',...
     ]);
 %=============================Edit for k 
n1 = uicontrol(gcf,'Style','text', ...
   'String','波的相位常数 k : ',...
   'Position',[5,187,100,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
n2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[110,190,80,20], ...
   'String', ...
   [num2str(k)],...
   'CallBack', ...
     [ 'cla;k=str2num(get(n2,''String''));',...
       'set(t2,''String'',[''波的相位常数 k = '',num2str(k)]);',...
     ]);
%================================ Push button
x1 = uicontrol(gcf,'Style','Push', ...
   'String','行波的动态模拟',...
   'Position',[50,120,140,30],...
   'CallBack',...
   'disp([a,w,k]);hb_m(a,w,k)');
x2 = uicontrol(gcf,'Style','push',...
   'String','驻波的动态模拟',...
   'Position',[50,50,140,30],...
   'Callback',...
   ['disp([a,w,k]);',...
'h=figure(2);',...
'set(h,''Position'',[60,100,580,380],''Color'',[0.7,0.7,0.7],''NumberTitle'',''off'',''Name'',''驻波的动态模拟'');',...
'z1 = uicontrol(gcf,''Style'',''text'',''String'',[''波的振幅 a =  '',num2str(a)],''HorizontalAlignment'',''Left'',''Position'',[5,360,110,15], ''BackgroundColor'',[0.7,0.7,0.7]);',...
'z1B= uicontrol(gcf,''Style'',''text'',''String'',[''波的角频率 w = '',num2str(w)],''HorizontalAlignment'',''Left'',''Position'',[125,360,120,15],''BackgroundColor'',[0.7,0.7,0.7]);',...
'z2 = uicontrol(gcf,''Style'',''text'',''String'',[''波的相位常数 k = '',num2str(k)],''HorizontalAlignment'',''Left'',''Position'',[255,360,130,15],''BackgroundColor'',[0.7,0.7,0.7]);',...
'y2 = uicontrol(gcf,''Style'',''push'',''String'',''暂停'',''Position'',[20,10,60,30],''Callback'',''pause(2)'');',...
'y3 = uicontrol(gcf,''Style'',''push'',''String'',''退出'',''Position'',[500,10,60,30], ''Callback'',''close''); ',...
'title=uicontrol(gcf, ''Style'',''text'',''Position'', [200,185, 160,20], ''String'',''入射波与反射波的动态模拟'',''Fontsize'',12);',...
'title=uicontrol(gcf, ''Style'',''text'',''Position'', [200,5, 160,20], ''String'',''合成波的动态模拟'',''Fontsize'',12);',...
'zb_m1(a,w,k)']);
x3 = uicontrol(gcf,'Style','push',...
   'String','退出',...
   'Position',[460,10,60,30],...
   'Callback','close');
x4 = uicontrol(gcf,'Style','push',...
   'String','暂停',...
   'Position',[300,10,60,30],...
   'Callback','pause(2)');