h0 = figure('menubar', 'none', 'NumberTitle', 'off', ...
    'position', [198 56 350 400], ...
    'name', '控制运动小球的角速度');
hAxes = axes('parent', h0, ...
    'position', [0.25 0.45 0.5 0.5], ...
    'visible', 'off');
t = 0 : 0.1 : 4*pi;
x = sin(t);
y = cos(t);
line(x, y);
axis equal
axis off
set(0, 'DefaultUicontrolBackgroundColor', get(h0, 'color'))
set(0, 'DefaultUicontrolFontsize', 12) 
hBobble = line('xdata', 0, ...       %产生小球
    'ydata', 1, ...
    'marker', 'o', ...
    'MarkerFaceColor', 'r', ...
    'markersize', 15, ...
    'erasemode', 'xor');
nPos = length(t);
iPos = 1;
delt = 0.01;
isPaused = false;
isForward = true;
btnStart_Callback = ['isPaused = false;',...
        'while ishandle(hFigure),',...
        'set(hBobble, ''xdata'', x(iPos), ''ydata'', y(iPos));',...
        'drawnow,',...
        'pause(delt),',...
        'iPos = iPos - (-1)^isForward;,',...
        'if iPos == nPos,',...
        'iPos = 1;',...
        'elseif iPos == 0,',...
        'iPos = nPos;',...
        'end,',...
        'if isPaused,',...
        'break,',...
        'end,',...
        'end'];
btnStart = uicontrol('parent', hFigure,...
    'units','points',...
    'tag','btnStart',...
    'style','pushbutton',...
    'string','开始',...
    'position',[30 50 50 20],...
    'callback', btnStart_Callback);
btnStop = uicontrol('parent',hFigure,...
    'units','points',...
    'tag','btnStop',...
    'style','pushbutton',...
    'string','停止',...
    'position',[100 50 50 20],...
    'callback','isPaused = true;');
btnReverse = uicontrol('parent', hFigure,...
    'units','points',...
    'tag','btnReverse',...
    'style','pushbutton',...
    'string','反向',...
    'position',[170 50 50 20],...
    'callback', 'isForward = ~isForward;');
btnClose = uicontrol('parent', hFigure,...
    'units','points',...
    'tag','btnClose',...
    'style','pushbutton',...
    'string','关闭',...
    'position',[100 20 50 20],...
    'callback',[...
        'isPaused = true;',...
        'closereq']);
slider = uicontrol('style','slider',...
    'parent',hFigure,...
    'units','points',...
    'tag','slider',...
    'value', 0.5,...
    'position',[40 90 190 15],...
    'callback',[...
        'val = get(slider, ''value'');,',...
        'delt = val/100 + 0.01;']);
text = uicontrol('parent', hFigure,...
    'units','points',...
    'tag','t1',...
    'style','text',...
    'fontsize',12,...
    'string','小球运动速度',...
    'position',[40 110 190 20]);
