clf, clear
h6=figure(1);
set(h6,'Position',[60,300,480,380],...
       'Color',[0.7,0.7,0.7],...
       'NumberTitle','off',...
       'Name','迈克尔逊干涉（等倾干涉）实验的计算机模拟')
axes( 'Position', [0.43 0.2, 0.55 0.55],...
      'Box', 'on', 'Color','k')
Lambda=632.8e-006;f=200;k=0;
Mikeson_m(Lambda,f,k)

   %calling 2nd RK
   
%====================== 'Fontname','Times NewRoman'系统需要支持文本框所设置的字体属性

t1 = uicontrol(gcf,'Style','text', ...
   'String','  迈克尔逊干涉（等倾干涉）的光强分布为： I = I(0) cos { 2πd cos [ atan ( r / f ) ] / λ } ^ 2',...
   'HorizontalAlignment','Left',...
   'Position',[5,360,450,15],...
   'BackgroundColor',[1,1,1]);
t1B= uicontrol(gcf,'Style','text', ...
   'String',...
      ['光波波长 λ (mm) = ',num2str(Lambda)],...
   'HorizontalAlignment','Left',...
   'Position',[15,335,180,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t2 = uicontrol(gcf,'Style','text', ...
   'String',...
      ['屏幕前透镜的焦距 f (mm) = ',num2str(f)],...  
   'HorizontalAlignment','Left',...
   'Position',[225,335,180,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t2B = uicontrol(gcf,'Style','text', ...
   'String',...
      ['两相干光束的程差 d (mm) = ',num2str(0.39-0.00005*k)],...
   'HorizontalAlignment','Left',...
   'Position',[15,305,200,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t3  = uicontrol(gcf,'Style','text', ...
   'String',...
      ['k = ',num2str(k)],...
   'HorizontalAlignment','Left',...
   'Position',[225,305,30,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
%=============================Edit for Lambda 
b1 = uicontrol(gcf,'Style','text', ...
   'String','光波波长 λ (mm) : ',...
   'Position',[15,242,100,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
b2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[115,245,75,20], ....
   'String', ...
   [num2str(Lambda)],...
   'CallBack', ...
     [ 'cla;Lambda=str2num(get(b2,''String''));',...
       'set(t1B,''String'',[''光波波长 λ (mm) =  '',num2str(Lambda)]);',...
     ]);
 %=============================Edit for f 
m1 = uicontrol(gcf,'Style','text', ...
   'String','透镜焦距 f (mm) :',...
   'Position',[15,197,100,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
m2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[115,200,75,20], ...
   'String', ...
   [num2str(f)],...
   'CallBack', ...
     [ 'cla;f=str2num(get(m2,''String''));',...
       'set(t2,''String'',[''屏幕前透镜的焦距 f (mm) = '',num2str(f)]);',...
     ]);
 %=============================Edit for k 
n1 = uicontrol(gcf,'Style','text', ...
   'String','光束程差 d (mm) : ',...
   'Position',[15,147,100,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
n2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[115,150,75,20], ...
   'String', ...
   [num2str(0.39-0.00005*k)],...
   'CallBack', ...
     [ 'cla;k=str2num(get(n2,''String''));',...
       'set(n2,''String'',num2str(0.39-0.00005*k));',...
       'set(t2B,''String'',[''两相干光束的程差 d (mm) = '',num2str(0.39-0.00005*k)]);',...
       'set(t3,''String'',[''k = '',num2str(k)]);',...
     ]);
%============================Slider for d 
g1 = uicontrol(gcf,'Style','text', ...
   'String','k : ',...
   'Position',[25,37,15,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
g1B=uicontrol(gcf,'Style','text', ...
   'String',' 光束程差 d (mm) = 0.39 - 0.00005 * k',...
   'Position',[5,100,195,15],...
   'BackgroundColor',[1,0.8,0.8]);
g2 = uicontrol(gcf,'Style','text', ...
   'String','0....................7...................15',...
   'Position',[45,60,150,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
g2B = uicontrol(gcf,...
   'Style','slider',...
   'Min' , 0 ,'Max', 15 , ...
   'SliderStep',[1/15 0.1], ...
   'Position',[45,40,150,20], ...
   'Value', k,...
   'CallBack', ...
     [ 'cla;k=get(g2B,''Value'');',...
       'set(t2B,''String'',[''两相干光束的程差 d (mm) = '',num2str(0.39-0.00005*k)]);',...
       'set(t3,''String'',[''k = '',num2str(k)]);',...
       'set(n2,''String'',num2str(0.39-0.00005*k));',...
     ]);
%================================ Push button
x1 = uicontrol(gcf,'Style','Push', ...
   'String','绘图',...
   'Position',[250,10,50,30],...
   'CallBack',...
   'disp([Lambda,f,k]);Mikeson_m(Lambda,f,k)');
x2 = uicontrol(gcf,'Style','push',...
   'String','退出',...
   'Position',[370,10,50,30],...
   'Callback','close');
