%GuiDm_21  GUI to show relationship figure
clf, clear
h6=figure(1);
set(h6,'Position',[60,300,480,380],...
       'Color',[0.7,0.7,0.7],...
       'NumberTitle','off',...
       'Name','共振现象的相图及动力学特征')
axes( 'Position', [0.43 0.2, 0.55 0.55],...
      'Box', 'on', 'Color','k')
tf=20*pi;wx=1/16;b=0.1;x0=0;v0=1;
APE_FI(tf,wx,b,x0,v0);
   %calling 2nd RK
%============================= 
t1 = uicontrol(gcf,'Style','text', ...
   'String',...
      ['运动时间 t =  ',num2str(tf)],...
   'HorizontalAlignment','Left',...
   'Position',[5,360,110,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t1B= uicontrol(gcf,'Style','text', ...
   'String',...
      ['频率比 η = ',num2str(wx)],...
   'HorizontalAlignment','Left',...
   'Position',[125,360,130,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t2 = uicontrol(gcf,'Style','text', ...
   'String',...
      ['阻尼系数 β = ',num2str(b)],...                        
   'HorizontalAlignment','Left',...
   'Position',[5,340,110,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t2B = uicontrol(gcf,'Style','text', ...
   'String',...
      ['初始位移 x(0) = ',num2str(x0)],...
   'HorizontalAlignment','Left',...
   'Position',[125,340,110,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
t3 = uicontrol(gcf,'Style','text', ...
   'String',...
      ['初始速度 v(0) =  ',num2str(v0)],...
   'HorizontalAlignment','Left',...
   'Position',[245,340,110,15],...
   'BackgroundColor',[0.7,0.7,0.7]);
%============================== Axis on/off
ckbox=uicontrol(gcf, 'Style','checkbox',...
        'Position', [30,305, 120,20], ...
        'String',' 坐标轴（开/关）', ...
        'BackgroundColor',[0.7,0.7,0.7],...
        'Value',1,...
        'CallBack',...
         ['ckv= get(ckbox,''Value'');if ckv==1,',...
          'axis on,elseif ckv==0, axis off, end ']);
%=============================Popup Menu
p1 = uicontrol('Style','Popup', ...
   'String',...
      'η= 1/16|η= 1/8|η= 1/4|η= 1/2|η= 1|η= 2|η= 4|η= 8|η= 16 ',...
   'Position',[315,360,80,20],...
   'Value',1,...
   'CallBack',...
   [...
    ' cla;cv=get(p1,''Value'');'...
    ' if cv==1, wx=1/16; end;'...
    ' if cv==2, wx=1/8; end;'...
    ' if cv==3, wx=1/4; end;'...
    ' if cv==4, wx=1/2; end;'...
    ' if cv==5, wx=1; end;'...
    ' if cv==6, wx=2; end;'...
    ' if cv==7, wx=4; end;'...
    ' if cv==8, wx=8; end;'...
    ' if cv==9, wx=16; end;'...
    ' set(t1B,''String'',[''频率比 η =  '',num2str(wx)]);',...
    ' set(m2, ''String'',[num2str(wx)]);',...
   ]);
p2 = uicontrol('Style','Popup', ...
   'String',...
      'β= 0.02|β= 0.05|β= 0.08|β= 0.1|β= 0.2|β= 0.5|β= 0.8|β= 1.0 ',...
   'Position',[395,360,80,20],...
   'Value',4,...
   'CallBack',...
   [...
    ' cla;cv=get(p2,''Value'');'...
    ' if cv==1, b =0.02; end;'...
    ' if cv==2, b =0.05; end;'...
    ' if cv==3, b =0.08; end;'...
    ' if cv==4, b =0.1; end;'...
    ' if cv==5, b =0.2; end;'...
    ' if cv==6, b =0.5; end;'...
    ' if cv==7, b =0.8; end;'...
    ' if cv==8, b =1.0; end;'...
    ' set(t2,''String'',[''阻尼系数 β= '',num2str(b)]);',...
    ' set(n2, ''String'',[num2str(b)]);',...
   ]);
%=============================Edit for tf 
b1 = uicontrol(gcf,'Style','text', ...
   'String','运动时间 t : ',...
   'Position',[25,257,65,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
b2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[90,260,70,20], ...
   'String', '62.8319',...
   'CallBack', ...
     [ 'cla;tf=str2num(get(b2,''String''));',...
       'set(t1,''String'',[''运动时间 t =  '',num2str(tf)]);',...
     ]);
 %=============================Edit for wx 
m1 = uicontrol(gcf,'Style','text', ...
   'String','频率比 η :',...
   'Position',[28,207,65,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
m2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[90,210,70,20], ...
   'String', ...
   [num2str(wx)],...
   'CallBack', ...
     [ 'cla;wx=str2num(get(m2,''String''));',...
       'set(t1B,''String'',[''频率比 η = '',num2str(wx)]);',...
     ]);
 %=============================Edit for b 
n1 = uicontrol(gcf,'Style','text', ...
   'String','阻尼系数 β : ',...
   'Position',[22,157,65,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
n2 = uicontrol(gcf,...
   'Style','edit',...
   'Position',[90,160,70,20], ...
   'String', ...
   [num2str(b)],...
   'CallBack', ...
     [ 'cla;b=str2num(get(n2,''String''));',...
       'set(t2,''String'',[''阻尼系数 β = '',num2str(b)]);',...
     ]);
%============================Slider for x0 
g1 = uicontrol(gcf,'Style','text', ...
   'String','初始位移x(0) : ',...
   'Position',[5,87,75,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
g1B = uicontrol(gcf,'Style','text', ...
   'String','-2.............0............2',...
   'Position',[80,107,113,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
g2 = uicontrol(gcf,...
   'Style','slider',...
   'Min' ,-2,'Max', 2, ...
   'SliderStep',[0.125 0.1],...
   'Position',[90,90,100,20], ...
   'Value', x0,...
   'CallBack', ...
     [ 'cla;x0=get(g2,''Value'');',...
       'set(t2B,''String'',[''初始位移 x(0) = '',num2str(x0)]);',...
     ]);
%=============================slider for v0 
r1 = uicontrol(gcf,'Style','text', ...
   'String','初始速度v(0) : ',...
   'Position',[5,25,75,20],...
   'BackgroundColor',[0.7,0.7,0.7]);
r1B = uicontrol(gcf,'Style','text', ...
   'String','-2............0............2',...
   'Position',[78,43,120,18],...
   'BackgroundColor',[0.7,0.7,0.7]);
r2 = uicontrol(gcf,...
   'Style','slider',...
   'Min' ,-2,'Max', 2, ...
   'SliderStep',[0.125 0.1],...
   'Position',[90,25,100,20], ...
   'Value', v0,...
   'CallBack', ...
     [ 'cla;v0=get(r2,''Value'');',...
       'set(t3,''String'',[''初始速度 v(0) = '',num2str(v0)]);',...
     ]);
%================================ Push button
x1 = uicontrol(gcf,'Style','Push', ...
   'String','绘图',...
   'Position',[250,10,50,30],...
   'CallBack',...
   'disp([tf,wx,b,x0,v0]);APE_FI(tf,wx,b,x0,v0);ckv= get(ckbox,''Value'');if ckv==1,axis on,elseif ckv==0,axis off,end');
x2 = uicontrol(gcf,'Style','push',...
   'String','退出',...
   'Position',[370,10,50,30],...
   'Callback','close');
