h0 = figure('menubar','none',...            %创建窗口
    'position',[200 60 450 450],...
    'numbertitle', 'off',...
    'name','例4.4.1：设置曲线的形状与颜色');
h1 = axes('parent',h0,...                   %创建坐标轴
    'position',[0.15 0.45 0.75 0.45],...
    'visible','on');
xlabel('自变量x');                          %x轴标签
ylabel('函数值y');                          %y轴标签
title('y=sin(x)');                          %标题
x = 0 : 0.1 : 2 * pi;                       %x轴数据
k = line(x,sin(x));                           %绘制数据曲线
set(0,'DefaultUicontrolfontsize',12)        %设置控件默认的字体大小
p1 = uicontrol('parent',h0,...                %创建【加号】按钮
    'string','加号',...
    'position',[80 120 50 30],...
    'callback','set(k,''marker'',''+'')');
p2 = uicontrol('parent',h0,...                %创建【圆圈】按钮
    'string','圆圈',...
    'position',[200 120 50 30],...
    'callback','set(k,''marker'',''o'')');
p3 = uicontrol('parent',h0,...                %创建【星号】按钮
    'string','星号',...
    'position',[320 120 50 30],...
    'callback','set(k,''marker'',''*'')');
c1 = uicontrol('parent',h0,...                %创建【红色】按钮
    'string','红色',...
    'position',[80 80 50 30],...
    'callback','set(k,''color'',''r'')');
c2 = uicontrol('parent',h0,...                %创建【绿色】按钮
    'string','绿色',...
    'position',[200 80 50 30],...
    'callback','set(k,''color'',''g'')');
c3 = uicontrol('parent',h0,...                %创建【蓝色】按钮
    'string','蓝色',...
    'position',[320 80 50 30],...
    'callback','set(k,''color'',''b'')');
s1 = uicontrol('parent',h0,...                %创建【实线】按钮
    'string','实线',...
    'position',[80 40 50 30],...
    'callback','set(k,''LineStyle'',''-'')');
s2 = uicontrol('parent',h0,...                %创建【虚线】按钮
    'string','虚线',...
    'position',[200 40 50 30],...
    'callback','set(k,''LineStyle'',''--'')');
s3 = uicontrol('parent',h0,...                %创建【无线】按钮
    'string','无线',...
    'position',[320 40 50 30],...
    'callback','set(k,''LineStyle'',''none'')');
