hFigure = figure('menubar', 'none', 'Visible', 'off');%创建隐藏的GUI窗口
hMenu = uimenu(hFigure, 'label', '&Tool', 'Accelerator', 'T');%创建菜单，并设置快捷键
hGridOn = uimenu(hMenu, 'label','grid on','Callback',...
    ['set(hGridOn,''checked'',''on'');',...
    'set(hGridOff,''checked'',''off'');',...
    'grid on']);  %创建菜单选项【Grid on】
hGridOff = uimenu(hMenu, 'label', 'grid off', 'checked', 'on', 'Callback',...
    ['set(hGridOff,''checked'',''on'');',...
    'set(hGridOn,''checked'',''off'');',...
    'grid off']);  %创建菜单选项【Grid off】
set(hFigure, 'Visible', 'on');  %显示窗口
