%% 创建一个隐藏的窗口
hFig = figure('Visible', 'off', 'menubar', 'none', 'NumberTitle', 'off', 'Name',...
    '菜单栏显示万年历', 'position', [500 300 300 100], 'DockControls', 'off');
%% 在窗口内创建一个菜单项
hMenu = uimenu(hFig, 'label', '', 'ForegroundColor', 'r');
%% 创建星期字符串
xingqi = {'日', '一', '二', '三', '四', '五', '六'};
%% 显示窗口
set(hFig, 'visible', 'on');
%% 创建定时器
t = timer('executionmode', 'fixedrate', 'period', 1, 'timerfcn',...
    ['if ishandle(hFig),',...
    'set(hMenu,''label'',[datestr(clock) ''星期'' xingqi{weekday(now)}]);',...
    'else,',...
    'stop(t),',...
    'delete(t),',...
    'end']);
%% 启动定时器
start(t);
